### ISSUE TITLE
[SR-9526] No public way to detect if XCTContext can run activity

### ISSUE THREAD

**Issue by stephencelis** [apple/swift-corelibs-xctest#357]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9526      |
   |Radar             | None         |
   |Original Reporter | @stephencelis      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Most recent \`swift test\` on macOS

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | XCTest    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f46c9e3552dd5f499882497bafd285c3

  </details>

**Issue Description:**

Right now XCTest doesn't provide a way to detect if activities can run:

<https://github.com/apple/swift/blob/518f26af062a70087d78459bd5f0e440258ff7fd/stdlib/public/Darwin/XCTest/XCTest.swift#L26>

This means it's impossible to build a library that uses activities in one configuration and not in another via the public API.

See:

[Activities are not available in SwiftPM projects (even on macOS) when using \`swift test\`](https://github.com/pointfreeco/swift-snapshot-testing/issues/121)

**Comment by grynspan** [comment]
Sorry for the (very!) late reply.

This API is part of the XCTest framework that ships in Xcode, not part of the open-source XCTest Swift library hosted here. If this is still an issue for you, please send Apple feedback using the [Feedback Assistant](https://feedbackassistant.apple.com). If you reply with the "FB" number you're given, I can make sure it is routed to the correct team and associated with this GitHub issue.
