### ISSUE TITLE
[SR-8826] XCTest - error: undefined reference to '$ss37_HashableTypedNativeDictionaryStorageCMa'

### ISSUE THREAD

**Issue by shahmishal** [apple/swift-corelibs-xctest#360]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8826      |
   |Radar             | None         |
   |Original Reporter | @shahmishal      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962949-def00adf-7b3f-4043-96ad-40f9ccf6f821.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | XCTest    |
   |Labels            | Bug        |
   |Assignee          | @compnerd      |
   |Priority          | Medium      |

   Watchers: @shahmishal

   md5: 52f94c91c4d06a574268b9f6fce9ee0e

  </details>

**Issue Description:**

Job URL: <https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_04/5665>

Full log attached to the JIRA

``` java
11:14:25 Linking /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_04/buildbot_incremental/swiftpm-linux-x86_64/x86_64-unknown-linux/release/SwiftPMPackageTests.xctest
11:14:26 /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_04/buildbot_incremental/xctest-linux-x86_64/libXCTest.so: error: undefined reference to '$ss37_HashableTypedNativeDictionaryStorageCMa'
11:14:26 /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_04/buildbot_incremental/xctest-linux-x86_64/libXCTest.so: error: undefined reference to '_swiftEmptyDictionaryStorage'
11:14:26 /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_04/buildbot_incremental/xctest-linux-x86_64/libXCTest.so: error: undefined reference to '$ss30_HashableTypedNativeSetStorageCMa'
11:14:26 /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_04/buildbot_incremental/xctest-linux-x86_64/libXCTest.so: error: undefined reference to '_swiftEmptySetStorage'
11:14:26 clang: error: linker command failed with exit code 1 (use -v to see invocation)
11:14:26 
11:14:26 <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
11:14:26 
11:14:26 --- bootstrap: error: build failed with exit status 1
11:14:26 /home/buildnode/jenkins/workspace/oss-swift-incrementa
```

**Comment by grynspan** [comment]
This issue was resolved with an llbuild change in 2018, looks like. Closing.
