### ISSUE TITLE
[SR-1164] XCTestCase testRunClass should be of type XCTestRun.Type in Swift

### ISSUE THREAD

**Issue by ec882e32-f2b6-4d2a-849c-98d6c7df0cfb** [apple/swift-corelibs-xctest#393]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1164      |
   |Radar             | rdar://25568830         |
   |Original Reporter | @modocache      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | XCTest    |
   |Labels            | Improvement, ClangImporter, SDKOverlay        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 8adee259f35799e321fb96cfd32cf201

  </details>

**Issue Description:**

See: <https://github.com/apple/swift-corelibs-xctest/pull/86#discussion_r58315662>

XCTest defines `XCTestCase.testRunClass` as an `AnyClass?`, and checks at runtime that this is a subclass of `XCTestRun`. It would be nicer if this was exported as `XCTestRun.Type` or `XCTestRun.Type?`.

Radar:

-   rdar://25568830

-   <https://openradar.appspot.com/25568830>

**Comment by grynspan** [comment]
Sorry for the late reply.

This is technically correct, but it would introduce a source incompatibility with the XCTest framework that ships with Xcode, where the relevant API is implemented in Objective-C and uses `Class` (which is imported into Swift as `AnyClass`.) So if somebody implements this method in their own `XCTestRun` subclass, it would fail to compile with a type mismatch under one implementation or the other.
