### ISSUE TITLE
Invoking `XCTContext.runActivity` from an `async` test causes runtime error

### ISSUE THREAD

**Issue by soumyamahunt** [apple/swift-corelibs-xctest#418]
When creating an activity from an async test, it causes `NSInternalInconsistencyException` with message `Current context must not be nil`:
> Current context must not be nil
(
	0   CoreFoundation                      0x00000001a2f291a8 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001a2c73e04 objc_exception_throw + 60
	2   Foundation                          0x00000001a3e60e88 -[NSCalendarDate initWithCoder:] + 0
	3   XCTestCore                          0x0000000100ca92a0 +[XCTContext currentContextInThread:] + 164
	4   XCTestCore                          0x0000000100ca76bc +[XCTContext currentContext] + 72
	5   libXCTestSwiftSupport.dylib         0x0000000119f628c4 $sSo10XCTContextC6XCTestE11runActivity5named5blockxSS_xSo11XCTActivity_pKXEtKlFZ + 64
	6   AsyncObjectsTests                   0x000000011cf71ef0 $s17AsyncObjectsTests09TaskQueueC0C12testactivityyyYaKF + 216
	7   AsyncObjectsTests                   0x000000011cf72185 $s17AsyncObjectsTests09TaskQueueC0C12testactivityyyYaKFyyYacfU_ToTQ0_ + 1
	8   AsyncObjectsTests                   0x000000011cf74375 $s17AsyncObjectsTests09TaskQueueC0C12testactivityyyYaKFyyYacfU_ToTATQ0_ + 1
	9   AsyncObjectsTests                   0x000000011ceddabd $sIeghH_ytIeghHr_TRTQ0_ + 1
	10  AsyncObjectsTests                   0x000000011cede0c1 $sIeghH_ytIeghHr_TRTATQ0_ + 1
	11  AsyncObjectsTests                   0x000000011ceddbd1 $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRyt_Tgq5TQ0_ + 1
	12  AsyncObjectsTests                   0x000000011cede249 $sxIeghHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRyt_Tgq5TATQ0_ + 1
	13  libswift_Concurrency.dylib          0x0000000223616ea1 _ZL23completeTaskWithClosurePN5swift12AsyncContextEPNS_10SwiftErrorE + 1
)

Here is a sample test that reproduces this error on Xcode 13.4.1 on macOS version 12.5:
```swift
func testactivity() async throws {
    XCTContext.runActivity(named: "test 1") { activity in
        XCTAssertTrue(true)
    }
}
```

Just removing the async specifier resolves the issue.

**Comment by soumyamahunt** [comment]
Seems like `XCTContext.runActivity` must be called from the main thread, applying `@MainActor` attribute to async method resolves the issue as well. Is this expected behavior?

**Comment by grynspan** [comment]
Sorry for the late reply.

This API is part of the XCTest framework that ships in Xcode, not part of the open-source XCTest Swift library hosted here. If this is still an issue for you, please send Apple feedback using the [Feedback Assistant](https://feedbackassistant.apple.com). If you reply with the "FB" number you're given, I can make sure it is routed to the correct team and associated with this GitHub issue.
