### ISSUE TITLE
[XCTest][Automation] Element with locator was not found from webdriver even it is exists (only on real device iOS 16.1/16.2beta)

### ISSUE THREAD

**Issue by StsiapanPal** [apple/swift-corelibs-xctest#423]
There is a different behaviour on same screen on simulator ios 16.1 iphone 12 and real device (SauceLabs) ios 16.1/16.2beta iPhone 12.

1. On simulator I am able to get element by AppiumBy.iOSClassChain - _**/XCUIElementTypeCell[name == 'address']/XCUIElementTypeTextView[name = 'detail_1']_, and test passes. Here is screenshot from appium inspector:

![Screenshot 2022-12-07 at 16 49 15](https://user-images.githubusercontent.com/94680206/206433909-14be9008-79d1-4b37-9d47-a5bfb305a487.png)

2. On real device ios 16.1/16.2beta only (iOS 15.6 issue is not reproducible) test is failing on same screen with error message Element with locator: AppiumBy.iOSClassChain: **/XCUIElementTypeCell[name == 'address']/XCUIElementTypeTextView[name = 'detail_1'] was not found from webdriver / root element after 20 seconds. Here is screenshot from appium inspector:

<img width="807" alt="Screenshot 2022-12-07 at 17 23 03" src="https://user-images.githubusercontent.com/94680206/206433975-952bc29d-21ae-422a-bc8c-509ff3ef5c8d.png">

**Expected Behavior**
On real device element should be found by AppiumBy.iOSClassChain: **/XCUIElementTypeCell[name == 'address']/XCUIElementTypeTextView[name = 'detail_1'] and test should pass

**Minimal Reproducible Example**
driver.findElement(AppiumBy.iOSClassChain("**/XCUIElementTypeCell[name == 'address']/XCUIElementTypeTextView[name = 'detail_1']"));

**Environment**
Operating system: mac
If running via appium CLI...
Appium CLI version (output of appium --version): 2.0.0-beta.44
Node.js version (output of node --version): v17.4.0
npm version (output of npm --version): 8.3.1
Real device or emulator/simulator: real device iOS 16.1

**Link to Appium Logs**
https://gist.github.com/StsiapanPal/ab82d6de6510cb29614f9d48d0f0f583

**Comment by StsiapanPal** [comment]
@weissi Could you please take a look? Or point me to right place where I can post this issue?

**Comment by grynspan** [comment]
Sorry for the late reply.

This appears to be an issue with XCUIAutomation, which is a part of the XCTest framework that ships with Xcode. swift-corelibs-xctest (this repository) does not support XCUIAutomation APIs. Please file a bug report using Apple's [Feedback Assistant](https://feedbackassistant.apple.com). Thanks!
