### ISSUE TITLE
Add `Sendable` conformances

### ISSUE THREAD

**Issue by fumoboy007** [apple/swift-corelibs-xctest#427]
The Darwin implementation of XCTest added [`Sendable`](https://developer.apple.com/documentation/swift/sendable) conformances to types like [`XCTestExpectation`](https://developer.apple.com/documentation/xctest/xctestexpectation). The open-source implementation should do the same.

**Comment by stmontgomery** [comment]
This happened in #414

**Comment by fumoboy007** [comment]
Thanks! Waiting for Swift 5.8 😁
