### ISSUE TITLE
[SR-15538] XCTAssert* should support async auto closures

### ISSUE THREAD

**Issue by tonyarnold** [apple/swift-corelibs-xctest#439]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15538      |
   |Radar             | None         |
   |Original Reporter | @tonyarnold      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 92389bef2056fcd8703f3b7ca3fd8cef

  </details>

**Issue Description:**

Currently, when trying to use XCTest to assert scenarios in test cases, if I try to use async code within any of the functions, I get the following: 

``` java
error: 'async' call in an autoclosure that does not support concurrency
XCTAssertTrue(try await someAsyncFunc())
```

It would be really really nice if this was supported.

**Comment by grynspan** [comment]
Duplicate of #419. Thank you for filing! We'll track this issue further over there.

**Comment by grynspan** [comment]
Duplicate of #419
