### ISSUE TITLE
The docs for Xcode's version of XCTest don't give any warning that they don't apply to this library

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-corelibs-xctest#462]

**Comment by grynspan** [comment]
To report issues against the documentation for the XCTest framework that ships with Xcode, please file feedback using Apple's [Feedback Assistant](https://feedbackassistant.apple.com). Thanks!

**Comment by dabrahams** [comment]
🤷 This library is built in cooperation with the development of that framework; IMO its a shared responsibility to work out clarity about what documentation applies where.

**Comment by dabrahams** [comment]
…and as usual, the Feedback Assistant website says
<img width="1301" alt="image" src="https://github.com/apple/swift-corelibs-xctest/assets/44065/3883c578-6078-460e-bc46-b685a4860058">
and that app won't let me create new feedback:

<img width="268" alt="image" src="https://github.com/apple/swift-corelibs-xctest/assets/44065/a41935a9-7c7d-4599-8325-460dfcf4b000">

So, I hope you'll forgive me for saying so but every time I'm asked to use feedback assistant I feel like I'm caught up in some kind of Kafkaesque scam.

**Comment by grynspan** [comment]
I feel your pain. I'm not sure how to resolve that for you. I'll inquire internally and see if I can get some advice for you.

**Comment by grynspan** [comment]
Would you mind trying again in about an hour? I'm told that there's an infrastructure issue that is being resolved at this moment.

**Comment by dabrahams** [comment]
Done; FB13034397
