### ISSUE TITLE
The test run summary should list the name of failed tests

### ISSUE THREAD

**Issue by tristanlabelle** [apple/swift-corelibs-xctest#472]
When running a large suite of tests, the XCTest output completes with a summary of the number of tests that failed, but one must search the logs manually to find out which tests failed, and this becomes more of a burden as the size of the test suite grows. It would be convenient to display a list of the names of tests that failed as part of the test run summary. This could be controlled by a command line switch.

```
Test Suite 'debug.xctest' failed at 2024-01-03 15:08:21.364
         Executed 24 tests, with 2 tests skipped and 5 failures (0 unexpected) in 197.131 (197.131) seconds
Test Suite 'All tests' failed at 2024-01-03 15:08:21.364
         Executed 24 tests, with 2 tests skipped and 5 failures (0 unexpected) in 197.131 (197.131) seconds
```

**Comment by compnerd** [comment]
It does already.  Please provide a reduced test case that demonstrates this.

```
Test Suite 'Selected tests' started at 2024-01-04 18:36:41.959
Test Suite 'AutoLayoutTests' started at 2024-01-04 18:36:41.959
Test Case 'AutoLayoutTests.testLayoutConstraintActivate' started at 2024-01-04 18:36:41.959
Test Case 'AutoLayoutTests.testLayoutConstraintActivate' passed (0.062 seconds)
Test Case 'AutoLayoutTests.testLayoutConstraintActivateList' started at 2024-01-04 18:36:42.021
Test Case 'AutoLayoutTests.testLayoutConstraintActivateList' passed (0.031 seconds)
Test Case 'AutoLayoutTests.testLayoutConstraintInactiveByDefault' started at 2024-01-04 18:36:42.052
S:\SourceCache\compnerd\swift-win32\Tests\AutoLayoutTests\AutoLayoutTests.swift:10: error: AutoLayoutTests.testLayoutConstraintInactiveByDefault : XCTAssertTrue failed -
Test Case 'AutoLayoutTests.testLayoutConstraintInactiveByDefault' failed (0.0 seconds)
Test Suite 'AutoLayoutTests' failed at 2024-01-04 18:36:42.052
         Executed 3 tests, with 1 failure (0 unexpected) in 0.093 (0.093) seconds
Test Suite 'Selected tests' failed at 2024-01-04 18:36:42.052
         Executed 3 tests, with 1 failure (0 unexpected) in 0.093 (0.093) seconds
```

**Comment by tristanlabelle** [comment]
It lists the failure at the point where the test is executed in the output, but does not offer a final summary of tests that have failed. When hundreds of tests are run, one has to scroll back and search the output for "failed" to gather a list of failed tests instead of having the list of failing test names readily provided in a final summary.

**Comment by compnerd** [comment]
Ah, I see.  I think that changing the output here is not really feasible (it is meant to match the behaviour of `xctest`).  I would recommend that you consider writing a custom observer and injecting that for the tests.
